### ISSUE TITLE
what is node and npm version requried ? 

### ISSUE THREAD

**Issue by azimshaik** [2Toad/node-teradata#46]
I have 
```
node v8.11.4
npm v5.6.0
```
when I tried `npm install node-teradata`

It throws
```
npm ERR! code E418
npm ERR! 418 I'm a teapot: node-teradata@latest
```

**Comment by JasonPierce** [comment]
@azimshaik your NPM and Node.js version should be fine. Are you behind a proxy? That error message seems related to https://github.com/npm/npm/issues/20791

FYI, I just tested this with NPM v6.1.0, and it installed without issue.
