### ISSUE TITLE
node-teradata relies on old version of JDBC

### ISSUE THREAD

**Issue by ethanrucinski** [2Toad/node-teradata#56]
node-teradata is using an old version of JDBC that uses an older version of java. 
Can we have the version of JDBC updated to 0.7.0 in the dependencies to use the newest version of java (0.12.1) instead of (0.11.1) which has a issues with node-gyp

**Comment by JasonPierce** [comment]
@ethanrucinski please submit a pull request, and I'll take a look at it

**Comment by ethanrucinski** [comment]
Hi Jason,

Happy to help. Any chance you can give me permission to create and commit to another branch to create the request?

Thanks,
Ethan

**Comment by JasonPierce** [comment]
Hey Ethan,

Just fork the repo and work off a new branch on your own fork. When your
work is ready for review, submit a PR against this upstream repo, and I’ll
merge it in.

https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork

Thanks for the help!
