### ISSUE TITLE
Receiving new error: java@0.12.1 install: `node-gyp rebuild` after using node-teradata for years.

### ISSUE THREAD

**Issue by HRS-Partners** [2Toad/node-teradata#63]
I have been using this package for 3+ years and never encountered an issue. Suddenly out of no where it is causing issues. I know it is this package as if I remove it from my package.json everything is fine.

Error below. Any help would be greatly appreciated.

`../src/utils.cpp: In function '_jobject* v8ToJava(JNIEnv*, v8::Local<v8::Value>)':
../src/utils.cpp:343:110: error: no matching function for call to 'v8::String::Value::Value(v8::Isolate*, v8::Local<v8::String>)'
     v8::String::Value val(v8::Isolate::GetCurrent(), arg->ToString(Nan::GetCurrentContext()).ToLocalChecked());
                                                                                                              ^
../src/utils.cpp:343:110: note: candidate is:
In file included from ../src/utils.h:6:0,
                 from ../src/utils.cpp:1:
/root/.node-gyp/8.6.0/include/node/v8.h:2743:14: note: v8::String::Value::Value(v8::Local<v8::Value>)
     explicit Value(Local<v8::Value> obj);
              ^
/root/.node-gyp/8.6.0/include/node/v8.h:2743:14: note:   candidate expects 1 argument, 2 provided
make: *** [Release/obj.target/nodejavabridge_bindings/src/utils.o] Error 1
make: Leaving directory `/usr/src/app/node_modules/java/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.19.76-linuxkit
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/src/app/node_modules/java
gyp ERR! node -v v8.6.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN tslint@5.20.1 requires a peer of typescript@>=2.3.0-dev || >=2.4.0-dev || >=2.5.0-dev || >=2.6.0-dev || >=2.7.0-dev || >=2.8.0-dev || >=2.9.0-dev || >=3.0.0-dev || >= 3.1.0-dev || >= 3.2.0-dev but none was installed.
npm WARN tsutils@2.29.0 requires a peer of typescript@>=2.1.0 || >=2.1.0-dev || >=2.2.0-dev || >=2.3.0-dev || >=2.4.0-dev || >=2.5.0-dev || >=2.6.0-dev || >=2.7.0-dev || >=2.8.0-dev || >=2.9.0-dev || >= 3.0.0-dev || >= 3.1.0-dev but none was installed.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! java@0.12.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the java@0.12.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-06-25T22_24_05_661Z-debug.log`

**Comment by JasonPierce** [comment]
We released v1.6.1 on 5/13/21, which wasn't supposed to contain any breaking changes. However, if you upgraded to this new version, it could be the culprit. Try rolling back to v1.6.0, and see if that resolves the issue.

**Comment by JasonPierce** [comment]
Closing @HRS-Partners since I haven't heard back from you. I can re-open if needed
